; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_dir = C:\.pio\build

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.f_cpu = 125000000L
lib_deps = 
	askuric/Simple FOC
	simplefoc/SimpleFOCDrivers@^1.0.9
build_type = debug
build_flags = 
	-Og
	-g3
	-DCORE_DEBUG_LEVEL=5
	-std=gnu++17
	-DSIMPLEFOC_DEBUG_RP2040
lib_archive = no
extra_scripts = pre:generate_compilation_database.py
upload_protocol = picotool
debug_tool = cmsis-dap
debug_server = 
	openocd
	-f interface/cmsis-dap.cfg
	-f target/rp2040.cfg
	-c "adapter speed 5000"
monitor_speed = 115200
